              Kuzmenko Dmytro
Wish_position:
    Level: Junior
    Language: PHP

Education:
    University: Taras Shevchenko National University of Kyiv
    Faculty: Faculty of Radio Physics, Electronics and Computer Systems
    Department: Nanophysics and Nanoelectronics
    Bachelor_training_program: Applied Physics
    Entrance_year: 2011
    Graduation_year: 2015

Skills:
    Languages: PHP
    Technologies: HTML, CSS, JavaScript, jQuery, MySQL(PDO), JSON,
                  Linux, Bootstrap3, Composer, Bower, Vagrant, Twig
    Frameworks: Laravel, Yii, Symfony2
    VCS: Git

Projects:
    -
        Name: Sparrow
        Language: PHP
        Framework: Symfony2
        Git: https://github.com/bionic-university/sparrow
    -
        Name: SymfonyJobeet
        Language: PHP
        Framework: Symfony2
        Git: https://github.com/repzy/SymfonyJobeet
    -
        Name: Yiiomg
        Language: PHP
        Framework: Yii(1.1)
        Git: https://github.com/repzy/Yiiomg

Courses:
    -
        Name: Tech Summer School
        Platform: BIONIC University
        Web: http://bionic-university.com/uk/

Languages:
    Ukrainian: Native
    English: Intermediate

Contacts:
    Address:
        city: Kiev
        street: Lomonosova 35
        subway: Vasylkivska
    E-mail: rrepzy@gmail.com
    LinkedIn: http://ua.linkedin.com/pub/dima-kuzmenko/a1/285/b65/
    Git: https://github.com/repzy
    Skype: rrepzy
    Phone: 0992298058