ens_jobeet_homepage:
    pattern:  /{_locale}/
    defaults: { _controller: EnsJobeetBundle:Job:index }
    requirements:
        _locale: uk|ru|en

EnsJobeetBundle_nolocalized:
    pattern: /
    defaults: { _controller: "EnsJobeetBundle:Job:index" }

EnsJobeetBundle_ens_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /{_locale}/job
    requirements:
        _locale: uk|ru|en

EnsJobeetBundle_ens_job_test:
    path: /test
    defaults: { _controller: EnsJobeetBundle:Test:index }

EnsJobeetBundle_category:
    pattern:  /{_locale}/category/{slug}
    defaults: { _controller: EnsJobeetBundle:Category:show, page: 1 }
    requirements:
        _locale: uk|ru|en

login:
    pattern: /login
    defaults: { _controller: EnsJobeetBundle:Default:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

EnsJobeetBundle_api:
    pattern: /api/{token}/jobs.{format}
    defaults: {_controller: "EnsJobeetBundle:Api:list"}
    requirements:
        _format: xml|json|yaml

EnsJobeetBundle_ens_affiliate:
    resource: "@EnsJobeetBundle/Resources/config/routing/affiliate.yml"
    prefix: /{_locale}/affiliate
    requirements:
        _locale: uk|ru|en

EnsJoneetBundle_changeLanguage:
    pattern: /change_language
    defaults: { _controller: "EnsJobeetBundle:Default:cahangeLanguage" }