ens_jobeet_homepage:
    path:     /
    defaults: { _controller: EnsJobeetBundle:Job:index }

EnsJobeetBundle_ens_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job
