ens_jobeet_homepage:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /

EnsJobeetBundle_ens_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

EnsJobeetBundle_ens_job_test:
    path: /test
    defaults: { _controller: EnsJobeetBundle:Test:index }

EnsJobeetBundle_category:
    pattern:  /category/{slug}
    defaults: { _controller: EnsJobeetBundle:Category:show, page: 1 }

login:
    pattern: /login
    defaults: { _controller: EnsJobeetBundle:Default:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

EnsJobeetBundle_api:
    pattern: /api/{token}/jobs.{format}
    defaults: {_controller: "EnsJobeetBundle:Api:list"}
    requirements:
        _format: xml|json|yaml

EnsJobeetBundle_ens_affiliate:
    resource: "@EnsJobeetBundle/Resources/config/routing/affiliate.yml"
    prefix: /affiliate