security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form-login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_AMIN }

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: 'ROLE_ADMIN' }
        main:
            entity: { class: Ens\JobeetBundle\Entity\User, property: username }

    encoders:
        Ens\JobeetBundle\Entity\User: sha512