ens_affiliate_new:
    pattern: /new
    defaults: { _controller: "EnsJobeetBundle:Affiliate:new" }

ens_affiliate_create:
    pattern: /create
    defaults: { _controller: "EnsJobeetBundle:Affiliate:create" }
    requirements: { _method: post }

ens_affiliate_wait:
    pattern: /wait
    defaults: { _controller: "EnsJobeetBundle:Affiliate:wait" }